name = "med-rev-flow"
compatibility_date = "2024-05-29"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"

[vars]
# Add any environment variables here

[[d1_databases]]
binding = "DB"
database_name = "med-rev-db"
database_id = "e5e0a6c5-c167-423d-806f-4971b6635d27"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "med-rev-storage"

[durable_objects]
bindings = [
  { name = "CONVERSATION_ROOM", class_name = "ConversationRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ConversationRoom"]
