import { Hono } from 'hono';
import { getInsurances, getInsurance, createInsurance, updateInsurance } from '../controllers/insurance.controller';
import { authenticate, requirePermission } from '../middleware/auth';
import { Permission } from '../middleware/permissions';
export const insuranceRouter = new Hono();
insuranceRouter.use('*', authenticate);
insuranceRouter.use('*', requirePermission(Permission.VIEW_INSURANCE));
insuranceRouter.get('/', getInsurances);
insuranceRouter.post('/', createInsurance);
insuranceRouter.get('/:id', getInsurance);
insuranceRouter.patch('/:id', updateInsurance);
