import { Hono } from 'hono';
import { getLeads, getLead, createLead, updateLead, addLeadActivity, getLeadStats } from '../controllers/leads.controller';
import { authenticate, requirePermission } from '../middleware/auth';
import { Permission } from '../middleware/permissions';
export const leadsRouter = new Hono();
leadsRouter.use('*', authenticate);
leadsRouter.use('*', requirePermission(Permission.VIEW_LEADS));
leadsRouter.get('/', getLeads);
leadsRouter.get('/stats', getLeadStats);
leadsRouter.post('/', createLead);
leadsRouter.get('/:id', getLead);
leadsRouter.patch('/:id', updateLead);
leadsRouter.post('/:id/activities', addLeadActivity);
