import { Router } from 'express';
import { getPriorAuths, getPriorAuth, createPriorAuth, updatePriorAuth, getPriorAuthStats } from '../controllers/priorAuth.controller';
import { authenticate } from '../middleware/auth';
export const priorAuthRouter = Router();
priorAuthRouter.use(authenticate);
priorAuthRouter.get('/', getPriorAuths);
priorAuthRouter.get('/stats', getPriorAuthStats);
priorAuthRouter.post('/', createPriorAuth);
priorAuthRouter.get('/:id', getPriorAuth);
priorAuthRouter.patch('/:id', updatePriorAuth);
